version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: brasil
      POSTGRES_PASSWORD: brasil2022
      POSTGRES_DB: default_database