version: '3'

services:
  database:
    restart: always
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: brasil
      POSTGRES_PASSWORD: brasil2022
      POSTGRES_DB: default_database
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ../data/db-data:/var/lib/postgresql/data

  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - 3001:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: brasil
      MB_DB_PASS: brasil2022
      MB_DB_HOST: database
    depends_on:
      - database
    links:
      - database